#!/usr/bin/env python3
"""
Generate a Minecraft-style crafting-grid image for every crafting recipe in the
mod (shaped + shapeless) and inline them into README.md under a marker-delimited
"## Crafting recipes (visual)" section.

Each image shows the 3x3 grid with ingredient icons placed (per the shaped
pattern, or filled in order for shapeless), an arrow, and the resulting item with
its count badge. BLOCKS render as wiki-style isometric 3D cubes (slabs as
half-cubes); flat items (tools, ingredients, food, doors) stay flat.

Icons resolve from:
  - mod item/block textures under assets/oceanstarter/textures/{item,block}/
  - block-items without a flat icon (stairs/slabs/walls/fences/...) fall back to
    the base block's texture
  - vanilla items/blocks: straight from the cached MC 1.21.1 client jar
  - ingredient tags (corals / coral_blocks): a representative vanilla coral

Run:  python3 scripts/gen-recipe-images.py [--no-readme]
"""
import json, os, glob, sys, zipfile
from PIL import Image, ImageDraw, ImageFont, ImageEnhance

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES  = os.path.join(ROOT, "src/main/resources")
RD   = os.path.join(RES, "data/oceanstarter/recipe")
ITEM = os.path.join(RES, "assets/oceanstarter/textures/item")
BLOCK= os.path.join(RES, "assets/oceanstarter/textures/block")
OUT  = os.path.join(ROOT, "docs/recipes")
README = os.path.join(ROOT, "README.md")
JAR  = os.path.expanduser("~/.gradle/caches/fabric-loom/1.21.1/minecraft-client.jar")
START, END = "<!-- RECIPE-IMAGES:START (generated by scripts/gen-recipe-images.py) -->", "<!-- RECIPE-IMAGES:END -->"

os.makedirs(OUT, exist_ok=True)
_jar = zipfile.ZipFile(JAR) if os.path.exists(JAR) else None
_tex_cache = {}

def _from_jar(kind, name):
    if not _jar: return None
    try:
        with _jar.open("assets/minecraft/textures/%s/%s.png" % (kind, name)) as f:
            return Image.open(f).convert("RGBA").copy()
    except KeyError:
        return None

def _mod_fallback(name):
    if name.startswith("driftwood"):
        return os.path.join(BLOCK, "driftwood_plank.png")
    for base in ("chiseled_prismarine_tiles", "polished_prismarine_bricks",
                 "pearl_block", "sea_glass", "prismarine_crystal_block",
                 "abyssal_pearl_block", "crushed_coral_block", "abyssal_coral_block"):
        if name.startswith(base):
            return os.path.join(BLOCK, base + ".png")
    return None

def load_tex(idv):
    """Raw 16x16 RGBA texture for an item/block id."""
    if idv in _tex_cache: return _tex_cache[idv]
    img = None
    ns, name = idv.split(":") if ":" in idv else ("minecraft", idv)
    if ns == "oceanstarter":
        for p in (os.path.join(ITEM, name + ".png"), os.path.join(BLOCK, name + ".png")):
            if os.path.exists(p):
                img = Image.open(p).convert("RGBA"); break
        if img is None:
            fb = _mod_fallback(name)
            if fb and os.path.exists(fb): img = Image.open(fb).convert("RGBA")
    else:
        # Some vanilla items have no flat icon under their own id — alias to the texture
        # that actually exists in the jar (e.g. panes render from the base glass texture).
        jarname = {"glass_pane": "glass"}.get(name, name)
        img = _from_jar("item", jarname) or _from_jar("block", jarname)
    if img is None:
        img = Image.new("RGBA", (16, 16), (255, 0, 255, 255)); print("  !! unresolved:", idv)
    if img.size != (16, 16):
        img = img.resize((16, 16), Image.NEAREST)
    _tex_cache[idv] = img
    return img

# (The old hand-rolled isometric cube/stair renderer lived here; it was retired
# when scripts/dump-item-icons.sh started providing REAL in-game GUI renders for
# every item — see load_icon/cell_display below. git history has the geometry.)

ICONS_SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "docs", "icons-src")
_icon_cache = {}

def load_icon(idv):
    """The REAL in-game GUI render for an item id, dumped as a transparent 128px
    PNG by scripts/dump-item-icons.sh. None if no dump exists for the id."""
    if idv in _icon_cache: return _icon_cache[idv]
    ns, name = idv.split(":") if ":" in idv else ("minecraft", idv)
    p = os.path.join(ICONS_SRC, "%s__%s.png" % (ns, name))
    img = Image.open(p).convert("RGBA") if os.path.exists(p) else None
    if img is None: print("  !! no dumped icon for", idv, "- using flat texture")
    _icon_cache[idv] = img
    return img

def cell_display(tex, idv, size):
    """Slot-ready icon: the real GUI render (exactly what the inventory shows —
    fences, gates, buttons, doors all correct) when a dump exists, else the flat
    16x16 texture as a fallback."""
    icon = load_icon(idv) if idv else None
    if icon is not None:
        s = size - 4
        return icon.resize((s, s), Image.LANCZOS)
    s = size - 12
    return tex.resize((s, s), Image.NEAREST)

# ---- ingredient -> display image --------------------------------------------
def ing_display(ing, size):
    if isinstance(ing, list): ing = ing[0]
    if isinstance(ing, dict):
        if "item" in ing: return cell_display(load_tex(ing["item"]), ing["item"], size)
        if "tag" in ing:
            # show a representative member for tag ingredients
            rep = "minecraft:tube_coral_block" if "block" in ing["tag"] else "minecraft:tube_coral"
            return cell_display(load_tex(rep), rep, size)
    return Image.new("RGBA", (size-12, size-12), (255, 0, 255, 255))

# ---- drawing ----------------------------------------------------------------
SLOT = 64; GAP = 6; PAD = 18
SLOTBG = (139, 139, 139, 255); HI = (255, 255, 255, 255); LO = (85, 85, 85, 255); PANEL = (198, 198, 198, 255)

def _font(sz):
    for p in ("/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"):
        try: return ImageFont.truetype(p, sz)
        except OSError: pass
    return ImageFont.load_default()

def slot(cv, x, y, disp=None, count=1, size=SLOT):
    d = ImageDraw.Draw(cv)
    d.rectangle([x, y, x+size-1, y+size-1], fill=SLOTBG)
    d.line([(x, y), (x+size-1, y)], fill=LO); d.line([(x, y), (x, y+size-1)], fill=LO)
    d.line([(x, y+size-1), (x+size-1, y+size-1)], fill=HI); d.line([(x+size-1, y), (x+size-1, y+size-1)], fill=HI)
    if disp is not None:
        px = x + (size - disp.width)//2; py = y + (size - disp.height)//2
        cv.alpha_composite(disp, (px, py))
        if count and count > 1:
            f = _font(22); s = str(count); bb = d.textbbox((0, 0), s, font=f)
            tx, ty = x+size-(bb[2]-bb[0])-6, y+size-(bb[3]-bb[1])-8
            d.text((tx+2, ty+2), s, font=f, fill=(50, 50, 50, 255))
            d.text((tx, ty), s, font=f, fill=(255, 255, 255, 255))

def render_recipe(r):
    shaped = "crafting_shaped" in r.get("type", "")
    cells = [None]*9
    if shaped:
        key = r.get("key", {})
        for ri, row in enumerate(r.get("pattern", [])):
            for ci, ch in enumerate(row):
                if ch != " " and ch in key:
                    cells[ri*3+ci] = ing_display(key[ch], SLOT)
    else:
        for i, ing in enumerate(r.get("ingredients", [])[:9]):
            cells[i] = ing_display(ing, SLOT)
    res = r.get("result", {})
    grid = 3*SLOT + 2*GAP; arrow = 58; rslot = 76
    W = PAD + grid + 24 + arrow + 24 + rslot + PAD; H = PAD + grid + PAD
    cv = Image.new("RGBA", (W, H), PANEL)
    for i in range(9):
        slot(cv, PAD + (i%3)*(SLOT+GAP), PAD + (i//3)*(SLOT+GAP), cells[i], 1)
    d = ImageDraw.Draw(cv); ax = PAD+grid+24; ay = H//2
    d.line([(ax, ay), (ax+arrow-14, ay)], fill=(80, 80, 80, 255), width=8)
    d.polygon([(ax+arrow-16, ay-16), (ax+arrow, ay), (ax+arrow-16, ay+16)], fill=(80, 80, 80, 255))
    rdisp = cell_display(load_tex(res.get("id", "")), res.get("id", ""), rslot)
    slot(cv, ax+arrow+24, (H-rslot)//2, rdisp, res.get("count", 1), size=rslot)
    return cv

def title_case(idv):
    return " ".join(w.capitalize() for w in idv.split(":")[-1].split("_"))

def main():
    rows = []; n = 0
    for f in sorted(glob.glob(os.path.join(RD, "*.json"))):
        r = json.load(open(f))
        if "crafting_" not in r.get("type", ""): continue
        stem = os.path.splitext(os.path.basename(f))[0]
        rel = "docs/recipes/%s.png" % stem
        render_recipe(r).convert("RGB").save(os.path.join(ROOT, rel))
        rows.append((title_case(r.get("result", {}).get("id", stem)), rel, r.get("result", {}).get("count", 1)))
        n += 1
    rows.sort(key=lambda t: t[0])
    print("[gen-recipe-images] rendered %d crafting recipe images" % n)
    if "--no-readme" in sys.argv: return
    lines = [START, "## Crafting recipes (visual)", "",
             "Every crafting-table recipe the mod adds, rendered as the grid + result "
             "(blocks shown as 3D, slabs as half-blocks). See **Recipes** above for smelting & stonecutter.", "",
             "<table>"]
    for i in range(0, len(rows), 2):
        lines.append("<tr>")
        for name, rel, cnt in rows[i:i+2]:
            cap = name + ((" ×%d" % cnt) if cnt > 1 else "")
            lines.append('<td align="center"><img src="%s" width="300"><br><sub>%s</sub></td>' % (rel, cap))
        lines.append("</tr>")
    lines += ["</table>", END]
    section = "\n".join(lines)
    md = open(README).read()
    if START in md and END in md:
        md = md[:md.index(START)] + section + md[md.index(END)+len(END):]
    elif "\n## License" in md:
        md = md.replace("\n## License", "\n" + section + "\n\n## License", 1)
    else:
        md = md.rstrip() + "\n\n" + section + "\n"
    open(README, "w").write(md)
    print("[gen-recipe-images] inlined %d images into README.md" % len(rows))

if __name__ == "__main__":
    main()
