#!/usr/bin/env python3
"""Generate the "## Recipes" section of README.md from the actual recipe JSON.

Parses every file in src/main/resources/data/oceanoverhaul/recipe/*.json and emits
a human-readable, grouped Markdown section. Run from the repo root:

    python3 scripts/gen-recipe-docs.py            # print the section to stdout
    python3 scripts/gen-recipe-docs.py --write     # splice it into README.md

The README must contain the *rendered* output (so it shows on GitHub); --write
replaces everything between the <!-- RECIPES:START --> / <!-- RECIPES:END -->
markers (creating the section at end-of-file if the markers are absent).

Accuracy rule: this reads the JSON only. It never invents ingredients, counts, or
recipes. If a recipe is removed from disk, it disappears here on the next run.
"""
import json
import glob
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECIPE_DIR = os.path.join(
    REPO_ROOT, "src", "main", "resources", "data", "oceanoverhaul", "recipe"
)
README = os.path.join(REPO_ROOT, "README.md")

START = "<!-- RECIPES:START (generated by scripts/gen-recipe-docs.py — do not edit by hand) -->"
END = "<!-- RECIPES:END -->"

# Tags used as ingredients render better as a plain-English "any X" phrase than
# as a raw tag id. Keyed by the bare tag path.
TAG_NAMES = {
    "corals": "Any Coral",
    "coral_blocks": "Any Coral Block",
}


def titleize(path):
    """oceanoverhaul:sea_glass -> Sea Glass ; minecraft:prismarine_shard -> Prismarine Shard."""
    bare = path.split(":", 1)[-1]
    return " ".join(w.capitalize() for w in bare.split("_"))


def ingredient_name(ing):
    """Resolve a single ingredient object ({"item":...} or {"tag":...}) to a readable name."""
    if "tag" in ing:
        bare = ing["tag"].split(":", 1)[-1]
        return TAG_NAMES.get(bare, "Any " + titleize(ing["tag"]))
    return titleize(ing["item"])


def result_name_count(result):
    name = titleize(result["id"])
    count = result.get("count", 1)
    return name, count


def md_escape(text):
    """Escape pipes so table cells don't break."""
    return text.replace("|", "\\|")


def shapeless_inputs(d):
    """Group identical shapeless ingredients into 'N× Name' and join with ' + '."""
    counts = {}
    order = []
    for ing in d["ingredients"]:
        name = ingredient_name(ing)
        if name not in counts:
            counts[name] = 0
            order.append(name)
        counts[name] += 1
    parts = []
    for name in order:
        n = counts[name]
        parts.append(f"{n}× {name}" if n > 1 else name)
    return " + ".join(parts)


def shaped_inputs(d):
    """Render a shaped recipe as the pattern grid plus a symbol legend.

    e.g.  `PCP / CPC / PCP` (P = Prismarine, C = Any Coral Block)
    Empty pattern cells (space) render as `.` so the grid shape is visible.
    """
    pattern = d["pattern"]
    grid = " / ".join("".join(c if c != " " else "." for c in row) for row in pattern)
    legend_parts = []
    # Preserve key declaration order (Python dicts keep insertion order; JSON load too).
    for sym, ing in d["key"].items():
        legend_parts.append(f"{sym} = {ingredient_name(ing)}")
    legend = ", ".join(legend_parts)
    return f"`{grid}`  ({legend})"


def cook_label(recipe_type):
    return {
        "minecraft:smelting": "Smelt",
        "minecraft:smoking": "Smoke",
        "minecraft:blasting": "Blast",
        "minecraft:campfire_cooking": "Campfire",
    }.get(recipe_type, "Cook")


def load_recipes():
    crafting = []  # (result_name, count, kind, inputs)
    cooking = []   # (result_name, source_name, verb, xp, time)
    stonecut = []  # (result_name, count, source_name)

    for path in sorted(glob.glob(os.path.join(RECIPE_DIR, "*.json"))):
        d = json.load(open(path))
        t = d["type"]
        if t == "minecraft:crafting_shaped":
            name, count = result_name_count(d["result"])
            crafting.append((name, count, "Shaped", shaped_inputs(d)))
        elif t == "minecraft:crafting_shapeless":
            name, count = result_name_count(d["result"])
            crafting.append((name, count, "Shapeless", shapeless_inputs(d)))
        elif t in (
            "minecraft:smelting",
            "minecraft:smoking",
            "minecraft:blasting",
            "minecraft:campfire_cooking",
        ):
            name, _ = result_name_count(d["result"])
            source = ingredient_name(d["ingredient"])
            cooking.append(
                (name, source, cook_label(t), d.get("experience"), d.get("cookingtime"))
            )
        elif t == "minecraft:stonecutting":
            name, count = result_name_count(d["result"])
            source = ingredient_name(d["ingredient"])
            stonecut.append((name, count, source))
        else:
            raise SystemExit(f"unknown recipe type {t!r} in {os.path.basename(path)}")

    crafting.sort(key=lambda r: (r[0], r[2]))
    cooking.sort(key=lambda r: r[0])
    stonecut.sort(key=lambda r: r[0])
    return crafting, cooking, stonecut


def render():
    crafting, cooking, stonecut = load_recipes()
    total = len(crafting) + len(cooking) + len(stonecut)
    out = []
    out.append(START)
    out.append("## Recipes")
    out.append("")
    out.append(
        f"All {total} recipes the mod adds, generated straight from the recipe JSON "
        "(`scripts/gen-recipe-docs.py`). Shaped patterns are shown row-by-row "
        "(`.` = empty slot) with a key legend; “Any Coral” / “Any Coral Block” "
        "means any of the five vanilla coral colors works."
    )
    out.append("")

    # --- Crafting ---
    out.append(f"### Crafting table ({len(crafting)})")
    out.append("")
    out.append("| Result | Qty | Kind | Ingredients |")
    out.append("| --- | --- | --- | --- |")
    for name, count, kind, inputs in crafting:
        out.append(f"| {md_escape(name)} | {count} | {kind} | {md_escape(inputs)} |")
    out.append("")

    # --- Smelting / cooking ---
    out.append(f"### Smelting & cooking ({len(cooking)})")
    out.append("")
    out.append("| Result | Process | Source | XP | Time (ticks) |")
    out.append("| --- | --- | --- | --- | --- |")
    for name, source, verb, xp, time in cooking:
        xp_s = ("%g" % xp) if xp is not None else "—"
        time_s = str(time) if time is not None else "—"
        out.append(
            f"| {md_escape(name)} | {verb} | {md_escape(source)} | {xp_s} | {time_s} |"
        )
    out.append("")

    # --- Stonecutting ---
    out.append(f"### Stonecutter ({len(stonecut)})")
    out.append("")
    out.append("| Result | Qty | Cut from |")
    out.append("| --- | --- | --- |")
    for name, count, source in stonecut:
        out.append(f"| {md_escape(name)} | {count} | {md_escape(source)} |")
    out.append("")
    out.append(END)
    return "\n".join(out), total


def main():
    section, total = render()
    if "--write" not in sys.argv:
        sys.stdout.write(section + "\n")
        sys.stderr.write(f"\n[gen-recipe-docs] {total} recipes rendered (not written; pass --write)\n")
        return

    with open(README, "r") as f:
        readme = f.read()

    if START in readme and END in readme:
        # Markers present — replace in place, preserving the section's location.
        pre = readme[: readme.index(START)]
        post = readme[readme.index(END) + len(END) :]
        new = pre + section + post
    elif "## License" in readme:
        # No markers — insert just before the License section (keeps License last).
        k = readme.index("## License")
        new = readme[:k].rstrip("\n") + "\n\n" + section + "\n\n" + readme[k:]
    else:
        # No markers, no License — append at end of file.
        new = readme.rstrip("\n") + "\n\n" + section + "\n"

    with open(README, "w") as f:
        f.write(new)
    sys.stderr.write(f"[gen-recipe-docs] wrote {total} recipes into {README}\n")


if __name__ == "__main__":
    main()
