#!/usr/bin/env python3
"""
Generate a Minecraft-style crafting-grid image for every crafting recipe in the
mod (shaped + shapeless) and inline them into README.md under a marker-delimited
"## Crafting recipes (visual)" section.

Each image shows the 3x3 grid with ingredient icons placed (per the shaped
pattern, or filled in order for shapeless), an arrow, and the resulting item with
its count badge. BLOCKS render as wiki-style isometric 3D cubes (slabs as
half-cubes); flat items (tools, ingredients, food, doors) stay flat.

Icons resolve from:
  - mod item/block textures under assets/oceanstarter/textures/{item,block}/
  - block-items without a flat icon (stairs/slabs/walls/fences/...) fall back to
    the base block's texture
  - vanilla items/blocks: straight from the cached MC 1.21.1 client jar
  - ingredient tags (corals / coral_blocks): a representative vanilla coral

Run:  python3 scripts/gen-recipe-images.py [--no-readme]
"""
import json, os, glob, sys, zipfile
from PIL import Image, ImageDraw, ImageFont, ImageEnhance

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES  = os.path.join(ROOT, "src/main/resources")
RD   = os.path.join(RES, "data/oceanstarter/recipe")
ITEM = os.path.join(RES, "assets/oceanstarter/textures/item")
BLOCK= os.path.join(RES, "assets/oceanstarter/textures/block")
OUT  = os.path.join(ROOT, "docs/recipes")
README = os.path.join(ROOT, "README.md")
JAR  = os.path.expanduser("~/.gradle/caches/fabric-loom/1.21.1/minecraft-client.jar")
START, END = "<!-- RECIPE-IMAGES:START (generated by scripts/gen-recipe-images.py) -->", "<!-- RECIPE-IMAGES:END -->"

os.makedirs(OUT, exist_ok=True)
_jar = zipfile.ZipFile(JAR) if os.path.exists(JAR) else None
_tex_cache = {}

def _from_jar(kind, name):
    if not _jar: return None
    try:
        with _jar.open("assets/minecraft/textures/%s/%s.png" % (kind, name)) as f:
            return Image.open(f).convert("RGBA").copy()
    except KeyError:
        return None

def _mod_fallback(name):
    if name.startswith("driftwood"):
        return os.path.join(BLOCK, "driftwood_plank.png")
    for base in ("chiseled_prismarine_tiles", "polished_prismarine_bricks",
                 "pearl_block", "sea_glass", "prismarine_crystal_block",
                 "abyssal_pearl_block", "crushed_coral_block", "abyssal_coral_block"):
        if name.startswith(base):
            return os.path.join(BLOCK, base + ".png")
    return None

def load_tex(idv):
    """Raw 16x16 RGBA texture for an item/block id."""
    if idv in _tex_cache: return _tex_cache[idv]
    img = None
    ns, name = idv.split(":") if ":" in idv else ("minecraft", idv)
    if ns == "oceanstarter":
        for p in (os.path.join(ITEM, name + ".png"), os.path.join(BLOCK, name + ".png")):
            if os.path.exists(p):
                img = Image.open(p).convert("RGBA"); break
        if img is None:
            fb = _mod_fallback(name)
            if fb and os.path.exists(fb): img = Image.open(fb).convert("RGBA")
    else:
        # Some vanilla items have no flat icon under their own id — alias to the texture
        # that actually exists in the jar (e.g. panes render from the base glass texture).
        jarname = {"glass_pane": "glass"}.get(name, name)
        img = _from_jar("item", jarname) or _from_jar("block", jarname)
    if img is None:
        img = Image.new("RGBA", (16, 16), (255, 0, 255, 255)); print("  !! unresolved:", idv)
    if img.size != (16, 16):
        img = img.resize((16, 16), Image.NEAREST)
    _tex_cache[idv] = img
    return img

def tag_tex(tag):
    name = tag.split(":")[-1]
    rep = "tube_coral_block" if "block" in name else "tube_coral"
    img = _from_jar("block" if "block" in name else "item", rep) or Image.new("RGBA", (16, 16), (220, 90, 160, 255))
    return img.resize((16, 16), Image.NEAREST) if img.size != (16, 16) else img

_BLOCK_NAMES = {
    "abyssal_coral_block", "abyssal_pearl_block", "barnacle_block", "crushed_coral_block",
    "pearl_block", "pearl_lantern", "prismarine_crystal_block", "salt_block", "sea_glass",
    "chiseled_prismarine_tiles", "polished_prismarine_bricks", "driftwood_plank",
    "driftwood_trapdoor", "glass", "oak_planks", "prismarine", "prismarine_bricks",
}
def is_block(idv):
    if idv.endswith(":coral_blocks"): return True
    if idv.endswith(":corals"): return False
    n = idv.split(":")[-1]
    if n.endswith("_door"): return False
    if n.startswith("driftwood"): return True
    if n.endswith("_slab") or n.endswith("_stairs") or n.endswith("_wall"): return True
    return n in _BLOCK_NAMES

# ---- isometric cube renderer (wiki-style) -----------------------------------
def _bright(im, f):
    r, g, b, a = im.split()
    rgb = ImageEnhance.Brightness(Image.merge("RGB", (r, g, b))).enhance(f)
    return Image.merge("RGBA", (*rgb.split(), a))

def _face(tex, size, O, e1, e2, br):
    # nu/nv separate so a non-square texture (e.g. a slab's bottom-half side strip)
    # maps with correct aspect instead of being squished to fill the face.
    nu, nv = tex.size; W, H = size
    m00, m01, m10, m11 = e1[0]/nu, e2[0]/nv, e1[1]/nu, e2[1]/nv
    det = m00*m11 - m01*m10
    if abs(det) < 1e-6: return None
    i00, i01, i10, i11 = m11/det, -m01/det, -m10/det, m00/det
    coeffs = (i00, i01, -(i00*O[0]+i01*O[1]), i10, i11, -(i10*O[0]+i11*O[1]))
    warped = tex.transform((W, H), Image.AFFINE, coeffs, resample=Image.NEAREST)
    mask = Image.new("L", (W, H), 0)
    poly = [O, (O[0]+e1[0], O[1]+e1[1]), (O[0]+e1[0]+e2[0], O[1]+e1[1]+e2[1]), (O[0]+e2[0], O[1]+e2[1])]
    ImageDraw.Draw(mask).polygon(poly, fill=255)
    warped.putalpha(Image.composite(warped.split()[3], Image.new("L", (W, H), 0), mask))
    return _bright(warped, br)

def iso_cube(tex, W=30, Vh=30, frac=1.0):
    tex = tex.convert("RGBA")
    if tex.size != (16, 16): tex = tex.resize((16, 16), Image.NEAREST)
    # For a partial-height block (slab, frac<1) the side faces only show the BOTTOM
    # frac of the block, so crop the texture to that strip instead of squishing the
    # full texture into the shortened face. Top face always uses the full texture.
    side = tex if frac >= 1.0 else tex.crop((0, 16 - max(1, int(round(16*frac))), 16, 16))
    toff = int(Vh*(1-frac)); vh = int(Vh*frac); cx = W
    A=(cx,toff); B=(2*W,toff+W//2); C=(cx,toff+W); D=(0,toff+W//2)
    E=(2*W,toff+W//2+vh); G=(0,toff+W//2+vh)
    cw, ch = 2*W+1, toff+W+vh+1
    cv = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    for O, e1, e2, br, ft in [
        (D, (A[0]-D[0],A[1]-D[1]), (C[0]-D[0],C[1]-D[1]), 1.00, tex),    # top
        (D, (C[0]-D[0],C[1]-D[1]), (G[0]-D[0],G[1]-D[1]), 0.80, side),   # left
        (B, (C[0]-B[0],C[1]-B[1]), (E[0]-B[0],E[1]-B[1]), 0.62, side)]:  # right
        f = _face(ft, (cw, ch), O, e1, e2, br)
        if f: cv.alpha_composite(f)
    return cv

def iso_stair(tex, W=30, Vh=30):
    """True iso stair: an upper step occupying the BACK half-depth (full height)
    plus a lower step on the FRONT half (half height), so the front tread + riser
    are visible. Steps along the j axis; same projection/brightness as iso_cube.
    Visible faces only (top + i=0 left + j=1 front), drawn back-to-front."""
    tex = tex.convert("RGBA")
    if tex.size != (16, 16): tex = tex.resize((16, 16), Image.NEAREST)
    def S(i, j, y):
        return (int(i*W + j*W), int((W//2) - i*(W//2) + j*(W//2) + y*Vh))
    cw, ch = 2*W+1, W+Vh+1
    cv = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    def quad(O, U, V, src, br):
        sub = tex.crop(src)
        f = _face(sub, (cw, ch), O, (U[0]-O[0], U[1]-O[1]), (V[0]-O[0], V[1]-O[1]), br)
        if f: cv.alpha_composite(f)
    # upper step (back: j 0..0.5, full height) — drawn first
    quad(S(0,0,0),     S(1,0,0),     S(0,0.5,0),   (0,0,16,8),  1.00)  # upper top
    quad(S(0,0,0),     S(0,0.5,0),   S(0,0,1),     (0,0,8,16),  0.80)  # upper left (i=0)
    quad(S(0,0.5,0),   S(1,0.5,0),   S(0,0.5,0.5), (0,0,16,8),  0.62)  # riser (j=0.5, y 0..0.5)
    # lower step (front: j 0.5..1, y 0.5..1) — drawn over the upper step
    quad(S(0,0.5,0.5), S(1,0.5,0.5), S(0,1,0.5),   (0,8,16,16), 1.00)  # lower tread
    quad(S(0,0.5,0.5), S(0,1,0.5),   S(0,0.5,1),   (8,8,16,16), 0.80)  # lower left (i=0)
    quad(S(0,1,0.5),   S(1,1,0.5),   S(0,1,1),     (0,8,16,16), 0.62)  # lower front (j=1)
    return cv

def cell_display(tex, idv, size):
    """Rendered icon ready to paste in a slot of `size`px: iso cube for blocks
    (slabs half-height, trapdoors 3/16, stairs two-tier), flat for items."""
    if idv and is_block(idv):
        n = idv.split(":")[-1]
        if n.endswith("_stairs"):
            cube = iso_stair(tex)
        else:
            frac = 0.5 if n.endswith("_slab") else 0.1875 if n.endswith("_trapdoor") else 1.0
            cube = iso_cube(tex, frac=frac)
        sc = min((size - 6) / cube.width, (size - 2) / cube.height)
        return cube.resize((max(1, int(cube.width*sc)), max(1, int(cube.height*sc))), Image.NEAREST)
    s = size - 12
    return tex.resize((s, s), Image.NEAREST)

# ---- ingredient -> display image --------------------------------------------
def ing_display(ing, size):
    if isinstance(ing, list): ing = ing[0]
    if isinstance(ing, dict):
        if "item" in ing: return cell_display(load_tex(ing["item"]), ing["item"], size)
        if "tag" in ing:
            tg = ing["tag"]
            return cell_display(tag_tex(tg), tg if is_block(tg) else None, size)
    return Image.new("RGBA", (size-12, size-12), (255, 0, 255, 255))

# ---- drawing ----------------------------------------------------------------
SLOT = 64; GAP = 6; PAD = 18
SLOTBG = (139, 139, 139, 255); HI = (255, 255, 255, 255); LO = (85, 85, 85, 255); PANEL = (198, 198, 198, 255)

def _font(sz):
    for p in ("/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"):
        try: return ImageFont.truetype(p, sz)
        except OSError: pass
    return ImageFont.load_default()

def slot(cv, x, y, disp=None, count=1, size=SLOT):
    d = ImageDraw.Draw(cv)
    d.rectangle([x, y, x+size-1, y+size-1], fill=SLOTBG)
    d.line([(x, y), (x+size-1, y)], fill=LO); d.line([(x, y), (x, y+size-1)], fill=LO)
    d.line([(x, y+size-1), (x+size-1, y+size-1)], fill=HI); d.line([(x+size-1, y), (x+size-1, y+size-1)], fill=HI)
    if disp is not None:
        px = x + (size - disp.width)//2; py = y + (size - disp.height)//2
        cv.alpha_composite(disp, (px, py))
        if count and count > 1:
            f = _font(22); s = str(count); bb = d.textbbox((0, 0), s, font=f)
            tx, ty = x+size-(bb[2]-bb[0])-6, y+size-(bb[3]-bb[1])-8
            d.text((tx+2, ty+2), s, font=f, fill=(50, 50, 50, 255))
            d.text((tx, ty), s, font=f, fill=(255, 255, 255, 255))

def render_recipe(r):
    shaped = "crafting_shaped" in r.get("type", "")
    cells = [None]*9
    if shaped:
        key = r.get("key", {})
        for ri, row in enumerate(r.get("pattern", [])):
            for ci, ch in enumerate(row):
                if ch != " " and ch in key:
                    cells[ri*3+ci] = ing_display(key[ch], SLOT)
    else:
        for i, ing in enumerate(r.get("ingredients", [])[:9]):
            cells[i] = ing_display(ing, SLOT)
    res = r.get("result", {})
    grid = 3*SLOT + 2*GAP; arrow = 58; rslot = 76
    W = PAD + grid + 24 + arrow + 24 + rslot + PAD; H = PAD + grid + PAD
    cv = Image.new("RGBA", (W, H), PANEL)
    for i in range(9):
        slot(cv, PAD + (i%3)*(SLOT+GAP), PAD + (i//3)*(SLOT+GAP), cells[i], 1)
    d = ImageDraw.Draw(cv); ax = PAD+grid+24; ay = H//2
    d.line([(ax, ay), (ax+arrow-14, ay)], fill=(80, 80, 80, 255), width=8)
    d.polygon([(ax+arrow-16, ay-16), (ax+arrow, ay), (ax+arrow-16, ay+16)], fill=(80, 80, 80, 255))
    rdisp = cell_display(load_tex(res.get("id", "")), res.get("id", ""), rslot)
    slot(cv, ax+arrow+24, (H-rslot)//2, rdisp, res.get("count", 1), size=rslot)
    return cv

def title_case(idv):
    return " ".join(w.capitalize() for w in idv.split(":")[-1].split("_"))

def main():
    rows = []; n = 0
    for f in sorted(glob.glob(os.path.join(RD, "*.json"))):
        r = json.load(open(f))
        if "crafting_" not in r.get("type", ""): continue
        stem = os.path.splitext(os.path.basename(f))[0]
        rel = "docs/recipes/%s.png" % stem
        render_recipe(r).convert("RGB").save(os.path.join(ROOT, rel))
        rows.append((title_case(r.get("result", {}).get("id", stem)), rel, r.get("result", {}).get("count", 1)))
        n += 1
    rows.sort(key=lambda t: t[0])
    print("[gen-recipe-images] rendered %d crafting recipe images" % n)
    if "--no-readme" in sys.argv: return
    lines = [START, "## Crafting recipes (visual)", "",
             "Every crafting-table recipe the mod adds, rendered as the grid + result "
             "(blocks shown as 3D, slabs as half-blocks). See **Recipes** above for smelting & stonecutter.", "",
             "<table>"]
    for i in range(0, len(rows), 2):
        lines.append("<tr>")
        for name, rel, cnt in rows[i:i+2]:
            cap = name + ((" ×%d" % cnt) if cnt > 1 else "")
            lines.append('<td align="center"><img src="%s" width="300"><br><sub>%s</sub></td>' % (rel, cap))
        lines.append("</tr>")
    lines += ["</table>", END]
    section = "\n".join(lines)
    md = open(README).read()
    if START in md and END in md:
        md = md[:md.index(START)] + section + md[md.index(END)+len(END):]
    elif "\n## License" in md:
        md = md.replace("\n## License", "\n" + section + "\n\n## License", 1)
    else:
        md = md.rstrip() + "\n\n" + section + "\n"
    open(README, "w").write(md)
    print("[gen-recipe-images] inlined %d images into README.md" % len(rows))

if __name__ == "__main__":
    main()
